[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.x"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["prisma/**/*.prisma"]

